version: '3.5'
services:
  na-client-bot:
    image: docker.pkg.github.com/news-aggregator-bot/artifactory/bepicky.na-client-bot
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - TG_CLIENT_TOKEN=${TG_CLIENT_TOKEN}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 60s
      timeout: 5s
      retries: 3
    ports:
      - 8079:8080
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
        reservations:
          cpus: "0.1"
          memory: "128M"
  na-admin-bot:
    image: docker.pkg.github.com/news-aggregator-bot/artifactory/bepicky.na-admin-bot
    environment:
      - TG_ADMIN_TOKEN=${TG_ADMIN_TOKEN}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 60s
      timeout: 5s
      retries: 3
    ports:
      - 8075:8080
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
        reservations:
          cpus: "0.1"
          memory: "128M"
networks:
  default:
    external:
      name: picky

