server:
  port: 8080
camel:
  main:
    banner-mode: "off"
  springboot:
    main-run-controller: true
bot:
  telegram:
    name: bepicky-tg-client
    token: ${TG_CLIENT_TOKEN}
management:
  endpoints:
    web:
      exposure:
        include: '*'
topics:
  category:
    cmd:
      start: category.cmd.start
      finish: category.cmd.finish
    list:
      start: category.list.start
      finish: category.list.finish
  reader:
    notification: reader.notification
  news:
    notification:
      new: newsnote.notification
      success: newsnote.notification.success
  lang:
    cmd:
      start: lang.cmd.start
      finish: lang.cmd.finish
eureka:
  instance:
    hostName: na-tg-client
  client:
    serviceUrl:
      defaultZone: http://na-registry:8761/eureka/
logging:
  level:
    org.springframework.security: INFO
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
spring:
  application:
    name: bepicky-client-bot
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
  config:
    import: "optional:configserver:"
    activate:
      on-profile: ${SPRING_PROFILES_ACTIVE}